//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppControlComprobantes.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteDeposito
    {
        public int Id { get; set; }
        public int ClienteRef { get; set; }
        public int UsuarioRef { get; set; }
        public string NumeroDeposito { get; set; }
        public int TipoMonedaRef { get; set; }
        public double Monto { get; set; }
        public string Fecha { get; set; }
        public string Motivo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoMoneda TipoMoneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
